//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>
#include "global.h"

extern void SpeakerOff(void);
extern void HapticOff(void);
extern U8 tick;
extern U8 spktime;
extern U8 haptime;


//-----------------------------------------------------------------------------
// RTC0ALARM_ISR
//-----------------------------------------------------------------------------
//
// RTC0ALARM ISR Content goes here. Remember to clear flag bits:
// RTC0CN0::ALRM (RTC Alarm Event Flag and Auto Reset Enable)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (RTC0ALARM_ISR, RTC0ALARM_IRQn)
{

	RTC0ADR = RTC0CN0;
	RTC0DAT &= ~RTC0CN0_RTC0AEN__ENABLED;
	while ((RTC0ADR & RTC0ADR_BUSY__BMASK) == RTC0ADR_BUSY__SET);

	RTC0ADR = RTC0CN0;
	RTC0DAT|= RTC0CN0_RTC0AEN__ENABLED;
	while ((RTC0ADR & RTC0ADR_BUSY__BMASK) == RTC0ADR_BUSY__SET);

	tick = true;

	if (spktime)
	{
		spktime--;
		if(!spktime) SpeakerOff();
	}


	if (haptime)
	{
		haptime--;
		if(!haptime) HapticOff();
	}

}

